{% set name = "pyuoi" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ea2267beff5dc2d11d4f5dec6ea2669ed360c239eb223250b3d0f78b4621602

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - scikit-learn

test:
  imports:
    - pyuoi

about:
  home: https://github.com/BouchardLab/pyuoi
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Union of Intersections Framework in Python

  description: |
    PyUoI contains implementations of Union of Intersections framework
    for a variety of penalized generalized linear models as well as
    dimensionality reductions techniques such as column subset selection
    and non-negative matrix factorization.
  doc_url: https://pyuoi.readthedocs.io/
  dev_url: https://github.com/BouchardLab/pyuoi

extra:
  recipe-maintainers:
    - pssachdeva
    - JesseLivezey
    - ajtritt
