{% set name = "pyuoi" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2bcb2c530fbbf587bb32e3090602b57074b163e81c21097a63845df64ec97e1b

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py27]
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - scikit-learn

test:
  imports:
    - pyuoi

about:
  home: https://github.com/BouchardLab/pyuoi
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'The Union of Intersections Framework in Python'

  description: |
    PyUoI contains implementations of Union of Intersections framework
    for a variety of penalized generalized linear models as well as
    dimensionality reductions techniques such as column subset selection
    and non-negative matrix factorization.
  doc_url: https://pyuoi.readthedocs.io/
  dev_url: https://github.com/BouchardLab/pyuoi

extra:
  recipe-maintainers:
    - pssachdeva
    - JesseLivezey
    - ajtritt
